# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
import json

from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(168, 81)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 10, 81, 16))
        self.label.setObjectName("label")
        self.okBtn = QtWidgets.QPushButton(Form)
        self.okBtn.setGeometry(QtCore.QRect(30, 40, 113, 32))
        self.okBtn.setObjectName("okBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Notification"))
        self.label.setText(_translate("Form", "Bad posture!"))
        self.okBtn.setText(_translate("Form", "OK"))


class NotificationDialog(QMainWindow, Ui_Form):
    def __init__(self, parent=None):
        super(NotificationDialog, self).__init__(parent)
        self.setupUi(self)

        self.okBtn.clicked.connect(self.close)
