# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(326, 218)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsWindow.sizePolicy().hasHeightForWidth())
        SettingsWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 291, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frequencySelector = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.frequencySelector.setMinimum(5)
        self.frequencySelector.setMaximum(60000)
        self.frequencySelector.setProperty("value", 10000)
        self.frequencySelector.setOrientation(QtCore.Qt.Horizontal)
        self.frequencySelector.setObjectName("frequencySelector")
        self.horizontalLayout.addWidget(self.frequencySelector)
        self.frequencyLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.horizontalLayout.addWidget(self.frequencyLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.windowOption = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.windowOption.setChecked(True)
        self.windowOption.setObjectName("windowOption")
        self.verticalLayout.addWidget(self.windowOption)
        self.builtinOption = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.builtinOption.setObjectName("builtinOption")
        self.verticalLayout.addWidget(self.builtinOption)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_2.addWidget(self.saveBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        SettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.label_2.setText(_translate("SettingsWindow", "Distance threshold:"))
        self.frequencyLabel.setText(_translate("SettingsWindow", "1000 ms"))
        self.label_3.setText(_translate("SettingsWindow", "Notification type:"))
        self.windowOption.setText(_translate("SettingsWindow", "window"))
        self.builtinOption.setText(_translate("SettingsWindow", "built-in"))
        self.saveBtn.setText(_translate("SettingsWindow", "Save"))
        self.cancelBtn.setText(_translate("SettingsWindow", "Cancel"))
